apiVersion: v1
kind: ReplicationController
metadata:
 name: app1
spec:
 replicas: 1
 selector:
    app: room
 template:
    metadata:
        labels:
            app: room
    spec:
        containers:
            - name: app1
            image: room-services
            ports:
            - containerPort: 8101