apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-vote-front3
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-vote-front3
    spec:
      containers:
      - name: azure-vote-front3
        image: freddybendezu/demo03:ver3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS1
          value: "azure-vote-back3"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front3
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front3