apiVersion: room-services/version1
kind: Deployment
metadata:
  name: room-services
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: room-services
    spec:
      containers:
      - name: room-services
        image: miregistro.azurecr.io/nuevosproyectos/hotel/room-services:version1
        ports:
        - containerPort: 8101
          name: room-services
---
apiVersion: v1
kind: Service
metadata:
  name: room-services
spec:
  ports:
  - port: 8101
  selector:
    app: room-services
---